// API 에러 문구 — 클라이언트가 그대로 화면에 띄우므로 요청자 언어(locale 쿠키)로 내려준다.

import { NextResponse } from 'next/server';
import { Msg, pick } from './i18n';
import { getLocale } from './locale';

/** 여러 라우트가 함께 쓰는 문구 */
export const E = {
  loginRequired: { ko: '카카오 로그인이 필요해요.', en: 'Please log in with Kakao.', es: 'Inicia sesión con Kakao.' },
  postNotFound: { ko: '포스트를 찾을 수 없어요.', en: 'Meetup not found.', es: 'Quedada no encontrada.' },
  notifNotFound: { ko: '알림을 찾을 수 없어요.', en: 'Alert not found.', es: 'Aviso no encontrado.' },
  badCategory: { ko: '올바르지 않은 카테고리입니다.', en: 'Unknown category.', es: 'Categoría desconocida.' },
  badRequest: { ko: '요청 형식이 올바르지 않습니다.', en: 'Malformed request.', es: 'Solicitud mal formada.' },
  badDateTime: { ko: '날짜와 시간을 올바르게 입력해주세요.', en: 'Enter a valid date and time.', es: 'Introduce una fecha y hora válidas.' },
  endBeforeStart: { ko: '종료 시간은 시작 시간보다 늦어야 해요.', en: 'The end time must be after the start time.', es: 'La hora de fin debe ser posterior a la de inicio.' },
  pastSlot: { ko: '이미 지난 시간으로는 모임을 만들 수 없어요.', en: 'You can’t create a meetup in the past.', es: 'No puedes crear una quedada en el pasado.' },
  pastMove: { ko: '지난 날짜로는 옮길 수 없어요.', en: 'You can’t move a meetup into the past.', es: 'No puedes moverla al pasado.' },
  location: { ko: '장소는 1~100자로 입력해주세요.', en: 'Place must be 1–100 characters.', es: 'El lugar debe tener entre 1 y 100 caracteres.' },
  memo: { ko: '메모는 500자 이하로 입력해주세요.', en: 'Note must be 500 characters or fewer.', es: 'La nota admite 500 caracteres como máximo.' },
  title: { ko: '제목은 100자 이하로 입력해주세요.', en: 'Title must be 100 characters or fewer.', es: 'El título admite 100 caracteres como máximo.' },
  capacity: { ko: '정원은 2~99 사이 숫자로 입력해주세요.', en: 'Capacity must be a number between 2 and 99.', es: 'El aforo debe ser un número entre 2 y 99.' },
  capacityBelowJoined: {
    ko: '현재 참가 인원({n}명)보다 적게 설정할 수 없어요.',
    en: 'Capacity can’t be lower than the current number of participants ({n}).',
    es: 'El aforo no puede ser menor que las personas ya apuntadas ({n}).',
  },
  postFull: { ko: '정원이 가득 차서 마감된 모임이에요.', en: 'This meetup is full.', es: 'Esta quedada está completa.' },
  authorCantLeave: {
    ko: '작성자는 참가를 취소할 수 없어요. 대신 포스트를 삭제해주세요.',
    en: 'The host can’t leave — delete the meetup instead.',
    es: 'Quien la creó no puede salir: borra la quedada.',
  },
  authorOnlyEdit: { ko: '작성자만 수정할 수 있어요.', en: 'Only the host can edit this.', es: 'Solo quien la creó puede editarla.' },
  authorOnlyDelete: { ko: '작성자만 삭제할 수 있어요.', en: 'Only the host can delete this.', es: 'Solo quien la creó puede borrarla.' },
  comment: { ko: '댓글은 1~300자로 입력해주세요.', en: 'Comments must be 1–300 characters.', es: 'Los comentarios deben tener entre 1 y 300 caracteres.' },
  commentNotFound: { ko: '댓글을 찾을 수 없어요.', en: 'Comment not found.', es: 'Comentario no encontrado.' },
  commentOwnerOnly: { ko: '본인 댓글만 삭제할 수 있어요.', en: 'You can only delete your own comments.', es: 'Solo puedes borrar tus propios comentarios.' },
  ruleNotFound: { ko: '반복 설정을 찾을 수 없어요.', en: 'Repeat setting not found.', es: 'No se encontró la repetición.' },
  ruleOwnerOnly: { ko: '만든 사람만 반복을 중단할 수 있어요.', en: 'Only the host can stop the repeat.', es: 'Solo quien la creó puede detener la repetición.' },
  rosterHostOnly: {
    ko: '명단에서 빼는 건 지난 모임에서 호스트만 할 수 있어요.',
    en: 'Only a host can remove someone, and only from a past meetup.',
    es: 'Solo un anfitrión puede quitar a alguien, y solo de una quedada pasada.',
  },
  notParticipant: { ko: '그 사람은 이 모임 명단에 없어요.', en: 'They aren’t in this meetup.', es: 'Esa persona no está en esta quedada.' },
  adminOnly: { ko: '관리자만 사용할 수 있어요.', en: 'Admins only.', es: 'Solo para administradores.' },
  photosPublicHostOnly: {
    ko: '사진 공개는 이 모임을 연 사람이나 관리자만 바꿀 수 있어요.',
    en: 'Only this meetup’s host or an admin can change who sees the photos.',
    es: 'Solo el anfitrión de esta quedada o un administrador puede cambiar quién ve las fotos.',
  },
  photosPublicAnon: {
    ko: '여기는 모두 익명이라 사진을 공개할 수 없어요. 사진에는 얼굴이 그대로 찍히거든요.',
    en: 'Everyone here is anonymous, so photos can’t be opened up — faces show in photos.',
    es: 'Aquí todos van en anónimo, así que las fotos no se pueden abrir: en ellas se ven las caras.',
  },
  adminOnlyReview: { ko: '관리자만 검토할 수 있어요.', en: 'Only admins can review suggestions.', es: 'Solo un administrador puede revisar las propuestas.' },
  requestNotFound: { ko: '제안을 찾을 수 없어요.', en: 'Suggestion not found.', es: 'Propuesta no encontrada.' },
  nickname: { ko: '닉네임은 20자 이하로 입력해주세요.', en: 'Nickname must be 20 characters or fewer.', es: 'El apodo admite 20 caracteres como máximo.' },
  nicknameBad: { ko: '닉네임 형식이 올바르지 않아요.', en: 'That nickname isn’t valid.', es: 'Ese apodo no es válido.' },
  anonNoSettle: {
    ko: '여기는 모두 익명이라 정산을 열 수 없어요. 금액 옆에 이름이 그대로 나오거든요.',
    en: 'Everyone here is anonymous, so settlements are off — they list names next to amounts.',
    es: 'Aquí todos van en anónimo, así que no hay cuentas: mostrarían nombres junto a los importes.',
  },
  anonNoFriendAdd: {
    ko: '여기는 모두 익명이라 명단에서 친구를 넣거나 요청할 수 없어요.',
    en: 'Everyone here is anonymous — you can’t add or friend people from this roster.',
    es: 'Aquí todos van en anónimo: no puedes añadir ni agregar a nadie desde esta lista.',
  },
  translateOff: {
    ko: '번역은 아직 준비 중이에요.',
    en: 'Translation isn’t set up yet.',
    es: 'La traducción aún no está configurada.',
  },
  translateFailed: {
    ko: '번역이 지금은 안 되네요. 잠시 뒤 다시 눌러보세요.',
    en: 'Couldn’t translate that just now — try again in a moment.',
    es: 'No se ha podido traducir ahora mismo; inténtalo en un momento.',
  },
  nameEn: { ko: '영어 이름은 30자 이하로 입력해주세요.', en: 'English name must be 30 characters or fewer.', es: 'El nombre en inglés admite 30 caracteres como máximo.' },
  nameEnBad: {
    ko: '영어 이름에는 로마자와 공백, - . \' 만 쓸 수 있어요.',
    en: 'English name can use Latin letters, spaces, and - . \' only.',
    es: 'El nombre en inglés solo admite letras latinas, espacios y - . \'.',
  },
  birthday: { ko: '생년월일을 올바르게 입력해주세요.', en: 'Enter a valid date of birth.', es: 'Introduce una fecha de nacimiento válida.' },
  gender: { ko: '성별을 선택해주세요.', en: 'Choose a gender.', es: 'Elige un género.' },
  locale: { ko: '지원하지 않는 언어입니다.', en: 'Unsupported language.', es: 'Idioma no admitido.' },
  noChange: { ko: '변경할 내용이 없습니다.', en: 'Nothing to update.', es: 'No hay nada que cambiar.' },
  kakaoRelogin: { ko: '카카오 재로그인이 필요해요.', en: 'Please log in with Kakao again.', es: 'Vuelve a iniciar sesión con Kakao.' },
  kakaoConsentCheck: {
    ko: '카카오에서 동의 상태를 확인하지 못했어요. 잠시 후 다시 시도해주세요.',
    en: 'Couldn’t check your Kakao consent. Please try again shortly.',
    es: 'No se pudo comprobar tu permiso de Kakao. Inténtalo de nuevo en un momento.',
  },
  kakaoRevoke: {
    ko: '카카오에서 동의를 철회하지 못했어요. 잠시 후 다시 시도해주세요.',
    en: 'Couldn’t revoke Kakao consent. Please try again shortly.',
    es: 'No se pudo retirar el permiso de Kakao. Inténtalo de nuevo en un momento.',
  },
  catName: { ko: '카테고리 이름은 1~20자로 입력해주세요.', en: 'Category name must be 1–20 characters.', es: 'El nombre de la categoría debe tener entre 1 y 20 caracteres.' },
  catColor: { ko: '색상을 골라주세요.', en: 'Pick a colour.', es: 'Elige un color.' },
  catDesc: { ko: '부제목은 1~50자로 입력해주세요.', en: 'Subtitle must be 1–50 characters.', es: 'El subtítulo debe tener entre 1 y 50 caracteres.' },
  catFeature: { ko: '원하는 기능은 1000자 이하로 입력해주세요.', en: 'Feature request must be 1000 characters or fewer.', es: 'La petición admite 1000 caracteres como máximo.' },
  catExists: { ko: '이미 있는 카테고리예요.', en: 'That category already exists.', es: 'Esa categoría ya existe.' },
  badStatus: { ko: '상태 값이 올바르지 않습니다.', en: 'Invalid status.', es: 'Estado no válido.' },
  avatarType: { ko: '이미지 파일만 올릴 수 있어요.', en: 'Only image files can be uploaded.', es: 'Solo se pueden subir imágenes.' },
  avatarSize: { ko: '사진 용량이 너무 커요. 다른 사진을 골라주세요.', en: 'That photo is too large. Please pick another.', es: 'Esa foto pesa demasiado. Elige otra.' },
  banned: {
    ko: '지금은 앱을 쓸 수 없어요. {left} 뒤에 다시 쓸 수 있어요.',
    en: 'You can’t use the app right now — it opens back up in {left}.',
    es: 'Ahora mismo no puedes usar la app: se abre de nuevo en {left}.',
  },
  banAdmin: { ko: '관리자는 정지할 수 없어요.', en: 'Admins can’t be suspended.', es: 'No se puede suspender a un administrador.' },
  banMinutes: { ko: '정지 기간이 올바르지 않아요.', en: 'That isn’t a valid duration.', es: 'Esa duración no es válida.' },
  pastDelete: {
    ko: '이미 지난 모임은 지울 수 없어요. 기록으로 남겨둬요. (지워야 한다면 관리자에게 말해주세요)',
    en: 'A meetup that already happened can’t be deleted — it stays as a record. Ask an admin if it really has to go.',
    es: 'Una quedada que ya ocurrió no se borra: queda como registro. Habla con un administrador si de verdad hay que quitarla.',
  },
  coHostIsAuthor: {
    ko: '모임을 만든 사람은 같이 여는 사람으로 넣을 수 없어요.',
    en: 'The person who made the meetup is already a host.',
    es: 'Quien creó la quedada ya es anfitrión.',
  },
  coHostNotFriend: {
    ko: '같이 여는 사람은 친구 중에서 고를 수 있어요.',
    en: 'You can only co-host with a friend.',
    es: 'Solo puedes co-organizar con un amigo.',
  },
  friendSelf: { ko: '자기 자신에게는 친구 요청을 보낼 수 없어요.', en: 'You can’t send yourself a friend request.', es: 'No puedes enviarte una solicitud a ti mismo.' },
  friendNoShared: {
    ko: '같은 모임에서 만난 사람에게만 친구 요청을 보낼 수 있어요.',
    en: 'You can only add someone you’ve shared a meetup with.',
    es: 'Solo puedes añadir a alguien con quien hayas coincidido en una quedada.',
  },
  friendExists: { ko: '이미 친구이거나 보낸 요청이 있어요.', en: 'You’re already friends, or a request is pending.', es: 'Ya sois amigos o hay una solicitud pendiente.' },
  friendNotFound: { ko: '친구 요청을 찾을 수 없어요.', en: 'Friend request not found.', es: 'Solicitud de amistad no encontrada.' },
  friendNotFriend: { ko: '친구만 모임에 넣을 수 있어요.', en: 'You can only add a friend to a meetup.', es: 'Solo puedes añadir a un amigo.' },
  friendAddOnly: {
    ko: '이 모임에 참가한 사람만 친구를 넣을 수 있어요.',
    en: 'Only someone in the meetup can add a friend to it.',
    es: 'Solo quien está en la quedada puede añadir a un amigo.',
  },
  friendAlreadyIn: { ko: '이미 이 모임에 참가하고 있어요.', en: 'They’re already in this meetup.', es: 'Ya está en esta quedada.' },
  friendAddPast: { ko: '지난 모임에는 넣을 수 없어요.', en: 'You can’t add anyone to a past meetup.', es: 'No puedes añadir a nadie a una quedada pasada.' },
  photoParticipantOnly: {
    ko: '이 모임에 참가한 사람만 사진을 올릴 수 있어요.',
    en: 'Only someone who was at the meetup can add photos.',
    es: 'Solo quien estuvo en la quedada puede añadir fotos.',
  },
  photoOwnerOnly: {
    ko: '올린 사람과 호스트만 지울 수 있어요.',
    en: 'Only whoever added it, or a host, can remove it.',
    es: 'Solo quien la subió, o un anfitrión, puede quitarla.',
  },
  photoNotFound: { ko: '사진을 찾을 수 없어요.', en: 'Photo not found.', es: 'Foto no encontrada.' },
  photoFull: { ko: '사진이 가득 찼어요.', en: 'This meetup has all the photos it can hold.', es: 'Esta quedada ya tiene todas las fotos que caben.' },
  photoBadUrl: { ko: '사진 주소가 올바르지 않아요.', en: 'That photo address isn’t valid.', es: 'La dirección de la foto no es válida.' },
  ratingClosed: {
    ko: '모임이 끝난 뒤에 평점을 매길 수 있어요.',
    en: 'You can rate this once the meetup is over.',
    es: 'Podrás puntuarla cuando la quedada termine.',
  },
  ratingParticipantOnly: {
    ko: '이 모임에 참가한 사람만 평점을 매길 수 있어요.',
    en: 'Only someone who was at the meetup can rate it.',
    es: 'Solo quien estuvo en la quedada puede puntuarla.',
  },
  ratingScore: {
    ko: '평점은 0.0~10.0 사이, 0.1 단위로 매겨주세요.',
    en: 'Ratings run 0.0–10.0 in steps of 0.1.',
    es: 'Las puntuaciones van de 0,0 a 10,0 en pasos de 0,1.',
  },
  reviewClosed: {
    ko: '모임이 끝난 뒤에 후기를 남길 수 있어요.',
    en: 'You can leave a review once the meetup is over.',
    es: 'Podrás dejar una reseña cuando la quedada termine.',
  },
  reviewParticipantOnly: {
    ko: '이 모임에 다녀온 사람만 후기를 남길 수 있어요.',
    en: 'Only someone who was at the meetup can review it.',
    es: 'Solo quien estuvo en la quedada puede reseñarla.',
  },
  reviewBody: {
    ko: '후기는 1~200자로 적어주세요.',
    en: 'A review is 1–200 characters.',
    es: 'Una reseña tiene entre 1 y 200 caracteres.',
  },
  settleNotFound: { ko: '정산을 찾을 수 없어요.', en: 'No settle-up found.', es: 'No hay ninguna cuenta que dividir.' },
  settleParticipantOnly: {
    ko: '모임에 참가한 사람만 정산을 만들 수 있어요.',
    en: 'Only someone in the meetup can start a settle-up.',
    es: 'Solo quien está en la quedada puede iniciar el reparto.',
  },
  settleOwnerOnly: {
    ko: '정산을 만든 사람만 고칠 수 있어요.',
    en: 'Only whoever started the settle-up can change it.',
    es: 'Solo quien inició el reparto puede cambiarlo.',
  },
  remindNobody: {
    ko: '다시 알릴 사람을 한 명 이상 골라주세요.',
    en: 'Pick at least one person to remind.',
    es: 'Elige al menos a una persona para recordárselo.',
  },
  settleItems: { ko: '정산 항목을 1~10개로 입력해주세요.', en: 'Add between 1 and 10 items.', es: 'Añade entre 1 y 10 conceptos.' },
  settleLabel: { ko: '항목 이름을 1~40자로 입력해주세요.', en: 'Each item needs a name of 1–40 characters.', es: 'Cada concepto necesita un nombre de 1 a 40 caracteres.' },
  settleAmount: {
    ko: '금액을 올바르게 입력해주세요 (예: 12.50).',
    en: 'Enter a valid amount (e.g. 12.50).',
    es: 'Introduce un importe válido (p. ej. 12.50).',
  },
  settleMembers: { ko: '나눠 낼 사람을 한 명 이상 골라주세요.', en: 'Pick at least one person to split with.', es: 'Elige al menos a una persona para dividir.' },
  settleExtra: {
    ko: '추가 인원은 0~50명 사이 숫자로 입력해주세요.',
    en: 'Extra people must be a whole number between 0 and 50.',
    es: 'Las personas de fuera deben ser un número entero entre 0 y 50.',
  },
  venmoId: {
    ko: 'Venmo 아이디는 영문·숫자·밑줄·하이픈 1~30자예요.',
    en: 'A Venmo username is 1–30 characters of letters, numbers, underscores or hyphens.',
    es: 'Un usuario de Venmo tiene de 1 a 30 caracteres: letras, números, guiones o guiones bajos.',
  },
  venmoNotId: {
    ko: '여기는 Venmo 아이디만 넣는 칸이에요. Venmo를 안 쓰시면 비워두세요 — 적어두면 그 아이디를 쓰는 다른 사람에게 돈이 갈 수 있어요.',
    en: 'This box takes a Venmo username only. If you don’t use Venmo, leave it empty — otherwise money can go to a stranger with that username.',
    es: 'Aquí va solo el usuario de Venmo. Si no usas Venmo, déjalo vacío: si no, el dinero puede ir a un desconocido con ese usuario.',
  },
  zelleId: {
    ko: 'Zelle은 전화번호나 이메일로 60자 이내로 입력해주세요.',
    en: 'Zelle takes a phone number or email, up to 60 characters.',
    es: 'Zelle admite un teléfono o correo, hasta 60 caracteres.',
  },
  ticketNotFound: { ko: '건의를 찾을 수 없어요.', en: 'Ticket not found.', es: 'Sugerencia no encontrada.' },
  ticketTitle: { ko: '한 줄 요약을 1~80자로 입력해주세요.', en: 'The summary must be 1–80 characters.', es: 'El resumen debe tener entre 1 y 80 caracteres.' },
  ticketBody: { ko: '자세한 내용은 2000자 이하로 입력해주세요.', en: 'Details must be 2000 characters or fewer.', es: 'El detalle admite 2000 caracteres como máximo.' },
  ticketKind: { ko: '건의 종류를 골라주세요.', en: 'Pick a ticket type.', es: 'Elige el tipo de sugerencia.' },
  adminNote: { ko: '답변은 500자 이하로 입력해주세요.', en: 'Reply must be 500 characters or fewer.', es: 'La respuesta admite 500 caracteres como máximo.' },
  tmdbSearch: { ko: '검색에 실패했어요.', en: 'Search failed.', es: 'La búsqueda falló.' },
  tmdbDetail: { ko: '상세 조회에 실패했어요.', en: 'Couldn’t load the details.', es: 'No se pudieron cargar los detalles.' },
  tmdbOff: { ko: 'TMDB_API_KEY가 설정되지 않았어요.', en: 'TMDB_API_KEY is not configured.', es: 'TMDB_API_KEY no está configurada.' },
  showtimesRequired: {
    ko: '가능한 상영 회차를 1개 이상 선택해주세요.',
    en: 'Pick at least one showtime.',
    es: 'Elige al menos una función.',
  },
  showtimesInvalid: {
    ko: '유효한 회차가 없습니다. 새로고침 후 다시 시도해주세요.',
    en: 'No valid showtimes. Refresh and try again.',
    es: 'No hay funciones válidas. Actualiza e inténtalo de nuevo.',
  },
  participantNotFound: { ko: '해당 참여자를 찾을 수 없어요.', en: 'Participant not found.', es: 'Participante no encontrado.' },
  adminKey: { ko: '관리자 키가 올바르지 않습니다.', en: 'Invalid admin key.', es: 'Clave de administrador no válida.' },
  scheduleArray: { ko: 'schedule 배열이 필요합니다.', en: 'A schedule array is required.', es: 'Se requiere un array schedule.' },
  scheduleShape: { ko: '형식이 올바르지 않은 항목이 있습니다.', en: 'Some entries have an invalid shape.', es: 'Algunas entradas tienen un formato no válido.' },
  userIdShowtimes: { ko: 'userId와 showtimeIds가 필요합니다.', en: 'userId and showtimeIds are required.', es: 'Se requieren userId y showtimeIds.' },
  kakaoKeyMissing: {
    ko: 'KAKAO_REST_API_KEY 환경변수가 설정되지 않았어요.',
    en: 'KAKAO_REST_API_KEY is not configured.',
    es: 'KAKAO_REST_API_KEY no está configurada.',
  },
  pushNotConfigured: {
    ko: '푸시 알림이 아직 설정되지 않았어요. 잠시 후 다시 시도해주세요.',
    en: 'Push notifications are not configured yet. Please try again later.',
    es: 'Las notificaciones push aún no están configuradas. Inténtalo más tarde.',
  },
  amcNotConfigured: {
    ko: 'AMC API가 설정되지 않았습니다. AMC_VENDOR_KEY와 AMC_THEATRE_ID 환경변수를 설정하세요.',
    en: 'The AMC API is not configured. Set AMC_VENDOR_KEY and AMC_THEATRE_ID.',
    es: 'La API de AMC no está configurada. Define AMC_VENDOR_KEY y AMC_THEATRE_ID.',
  },
  signupFull: {
    ko: '신청이 다 찼어요. 자리가 나면 다시 신청할 수 있어요.',
    en: 'The list is full. You can sign up if someone drops out.',
    es: 'La lista está completa. Podrás apuntarte si alguien la deja.',
  },
  noticeTitle: { ko: '공지 제목은 1~60자로 입력해주세요.', en: 'The notice title must be 1–60 characters.', es: 'El título del aviso debe tener entre 1 y 60 caracteres.' },
  noticeBody: { ko: '공지 내용은 1000자 이하로 입력해주세요.', en: 'The notice must be 1000 characters or fewer.', es: 'El aviso admite 1000 caracteres como máximo.' },
  noticeNotFound: { ko: '공지를 찾을 수 없어요.', en: 'Notice not found.', es: 'Aviso no encontrado.' },
  amcNoShowtimes: {
    ko: 'AMC API에서 The Odyssey 회차를 찾지 못했습니다.',
    en: 'No The Odyssey showtimes found via the AMC API.',
    es: 'No se encontraron funciones de The Odyssey en la API de AMC.',
  },
};

/** 요청자 언어로 에러 JSON을 만든다 */
export async function errJson(msg: Msg, status: number, vars?: Record<string, string | number>) {
  return NextResponse.json({ error: pick(await getLocale(), msg, vars) }, { status });
}
